server:
  port: 8000
spring:
  cloud:
    config:
      server:
        git:
          #服务的git仓库地址
          uri: https://github.com/Zhrey/candidateConfig.git
          #配置文件所在的目录
          search-paths: /*
          username: zhrey
          password: ZHR0743@qq.com
