server:
  port: 8000
spring:
  application:
    name: candidate-config
  cloud:
    config:
      server:
        git:
          #服务的git仓库地址
          uri: https://github.com/Zhrey/candidateConfig.git
          #配置文件所在的目录
          search-paths: /*
          username: zhrey
          password: ZHR0743@qq.com
eureka:
  instance:
    prefer-ip-address: true
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8002/eureka